apiVersion: v1
kind: Service
metadata:
  name: {{ "{{" }} .Release.Name {{ "}}" }}-svc
  namespace: {{ "{{" }} .Release.Namespace {{ "}}" }}
spec:
  type: ClusterIP
  selector:
    app: {{ "{{" }} .Release.Name {{ "}}" }}
  ports:
    - name: http
      port: {{ SERVICE_PORT | default: 3000 }}
      targetPort: {{ CONTAINER_PORT | default: 3000 }}
      protocol: TCP
